version: "3.9"

services:
  app:
    container_name: laravel_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=Takeru
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - db
      - redis

    networks:
      - app_network

  db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=Takeru
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

    networks:
      - app_network

  redis:
    container_name: redis_cache
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

    networks:
      - app_network

  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    # command: ["npm", "start"]
    command: ["sleep", "infinity"]

    networks:
      - app_network

volumes:
  db-data:
  redis-data:

networks:
  app_network:
    driver: bridge
