const DEFAULT_ITEM_TO_BUY = 10;
const DEFAULT_OPTION_OF_ITEM_TO_BUY = Array.from({length: DEFAULT_ITEM_TO_BUY}, (_, i) => i + 1);
const DEFAULT_PAGE = 1;
const DEFAULT_PAGE_SIZE = 10;

export {
  DEFAULT_ITEM_TO_BUY,
  DEFAULT_OPTION_OF_ITEM_TO_BUY,
  DEFAULT_PAGE,
  DEFAULT_PAGE_SIZE,
};
